# Generated by Django 6.0.1 on 2026-01-27 04:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('game', models.CharField(choices=[('magic', 'Magic: The Gathering'), ('pokemon', 'Pokémon TCG'), ('yugioh', 'Yu-Gi-Oh!'), ('lorcana', 'Disney Lorcana'), ('onepiece', 'One Piece Card Game'), ('fab', 'Flesh and Blood')], max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_cards', models.PositiveIntegerField(default=0)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card Set',
                'verbose_name_plural': 'Card Sets',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('game', models.CharField(choices=[('magic', 'Magic: The Gathering'), ('pokemon', 'Pokémon TCG'), ('yugioh', 'Yu-Gi-Oh!'), ('lorcana', 'Disney Lorcana'), ('onepiece', 'One Piece Card Game'), ('fab', 'Flesh and Blood')], db_index=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare'), ('special', 'Special')], default='common', max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('image_url_hires', models.URLField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, help_text='7-day rolling average sale price', max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foil_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='catalog.cardset')),
            ],
            options={
                'verbose_name': 'Card Product',
                'verbose_name_plural': 'Card Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('near_mint', 'Near Mint (NM)'), ('lightly_played', 'Lightly Played (LP)'), ('moderately_played', 'Moderately Played (MP)'), ('heavily_played', 'Heavily Played (HP)'), ('damaged', 'Damaged (DMG)')], default='near_mint', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('es', 'Español'), ('jp', '日本語'), ('kr', '한국어'), ('cn', '中文'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano')], default='pt', max_length=5)),
                ('is_foil', models.BooleanField(default=False)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.cardproduct')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('shipping_name', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=50)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(default='Brazil', max_length=50)),
                ('payment_method', models.CharField(default='stripe', max_length=50)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('condition', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.listing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.cardproduct')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Brazil', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('near_mint', 'Near Mint (NM)'), ('lightly_played', 'Lightly Played (LP)'), ('moderately_played', 'Moderately Played (MP)'), ('heavily_played', 'Heavily Played (HP)'), ('damaged', 'Damaged (DMG)')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('es', 'Español'), ('jp', '日本語'), ('kr', '한국어'), ('cn', '中文'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano')], max_length=5)),
                ('is_foil', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.listing')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.cardproduct')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.seller')),
            ],
            options={
                'verbose_name': 'Sale History',
                'verbose_name_plural': 'Sale History',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.seller'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.seller'),
        ),
        migrations.AddIndex(
            model_name='cardproduct',
            index=models.Index(fields=['game', 'name'], name='catalog_car_game_09f0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='cardproduct',
            index=models.Index(fields=['game', 'rarity'], name='catalog_car_game_293fb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardproduct',
            unique_together={('game', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='salehistory',
            index=models.Index(fields=['product', 'sold_at'], name='catalog_sal_product_f3678f_idx'),
        ),
        migrations.AddIndex(
            model_name='salehistory',
            index=models.Index(fields=['product', 'is_foil', 'sold_at'], name='catalog_sal_product_37318b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['product', 'condition', 'status'], name='catalog_lis_product_6c271a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='catalog_lis_seller__b4d1ae_idx'),
        ),
    ]
