# Generated by Django 6.0.1 on 2026-01-27 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_delivered_at_order_notes_order_shipped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('near_mint', 'Near Mint (NM)'), ('lightly_played', 'Lightly Played (LP)'), ('moderately_played', 'Moderately Played (MP)'), ('heavily_played', 'Heavily Played (HP)'), ('damaged', 'Damaged (DMG)')], default='near_mint', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='catalog.cardproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('foil_market_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_points', to='catalog.cardproduct')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='unique_daily_price')],
            },
        ),
    ]
