# Generated by Django 6.0.1 on 2026-01-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_pricealert_productpricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('game', models.CharField(choices=[('magic', 'Magic: The Gathering'), ('pokemon', 'Pokémon TCG'), ('yugioh', 'Yu-Gi-Oh!'), ('lorcana', 'Disney Lorcana'), ('onepiece', 'One Piece Card Game'), ('fab', 'Flesh and Blood')], default='magic', max_length=20)),
                ('format', models.CharField(blank=True, help_text='e.g. Standard, Commander', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_commander', models.BooleanField(default=False)),
                ('is_sideboard', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='builder.deck')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_usages', to='catalog.cardproduct')),
            ],
            options={
                'unique_together': {('deck', 'product', 'is_sideboard')},
            },
        ),
    ]
